controller_frequency: 10
conservative_reset_dist: 1.0

TrajectoryPlannerROS:

    max_vel_x: 0.50
    min_vel_x: -0.1
    max_vel_theta: 3.0
    min_vel_theta: -3.0
    min_in_place_vel_theta: 1.0
    escape_vel: -0.10

    acc_lim_theta: 10.0
    acc_lim_x: 2.0
    acc_lim_y: 2.0

    holonomic_robot: false

    sim_time: 1.0

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.5
    latch_xy_goal_tolerance: false

    meter_scoring: true
