base_local_planner: "teb_local_planner/TebLocalPlannerROS"

recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

aggressive_reset:
    reset_distance: 0.0

TebLocalPlannerROS:
    ## Costmap converter plugin   
    costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
    #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
    #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
    # costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
    #costmap_converter_plugin: "" # deactivate plugin
    costmap_converter_spin_thread: True
    costmap_converter_rate: 10
   
   
    ## Configure plugins (namespace move_base/TebLocalPlannerROS/PLUGINNAME)
    costmap_converter/CostmapToPolygonsDBSMCCH:
        cluster_max_distance: 0.25
        cluster_min_pts: 5 
        cluster_max_pts: 75

        ransac_inlier_distance: 0.15
        ransac_min_inliers: 10
        ransac_no_iterations: 2000
        ransac_remainig_outliers: 3
        ransac_convert_outlier_pts: True
        ransac_filter_remaining_outlier_pts: False
        convex_hull_min_pt_separation: 0.1

    odom_topic: /odometery/filtered
    map_frame: /map
       
    # Trajectory
     
    teb_autosize: True
    dt_ref: 0.4
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: False
    # This is so we stick to the global plan and don't make s's 
    # max_global_plan_lookahead_dist: 3.0
    feasibility_check_no_poses: 5

    global_plan_viapoint_sep: -1
       
    # Robot
            
    max_vel_x: 0.8
    max_vel_x_backwards: 0.5
    max_vel_theta: 1.0 
    acc_lim_x: 4.0
    # If this is low, we overshoot on a rotate
    acc_lim_theta: 5
    min_turning_radius: 0.01
    wheelbase: 0.1
    footprint_model: 
       type: "polygon"
       vertices: [
           [  0.40,  0.36],
           [ -0.43,  0.36],
           [ -0.43,  0.08],
           [ -0.54,  0.08],
           [ -0.54, -0.08],
           [ -0.43, -0.08],
           [ -0.43, -0.36],
           [  0.40, -0.36],
       ]
   
    # GoalTolerance
       
    xy_goal_tolerance: 1.0
    yaw_goal_tolerance: 1.5
    # free_goal_vel: False
       
    # Obstacles
       
    min_obstacle_dist: 0.025
    # inflation_dist: 0.20
    # include_costmap_obstacles: True
    # costmap_obstacles_behind_robot_dist: 1.0
    # obstacle_poses_affected: 30
   
    # Optimization
       
    no_inner_iterations: 4
    no_outer_iterations: 3
    optimization_activate: True
    optimization_verbose: False
   #  penalty_epsilon: 0.04
    weight_max_vel_x: 250 
    weight_max_vel_theta: 200 
   #  weight_acc_lim_x: 1
    weight_acc_lim_theta: 200
   #  weight_kinematics_nh: 1000
    weight_kinematics_forward_drive: 300
    weight_kinematics_turning_radius: 100
   #  weight_optimaltime: 1
   #  weight_obstacle: 20
   #  weight_dynamic_obstacle: 10 # not in use yet
   # #  alternative_time_cost: False # not in use yet
   #  selection_alternative_time_cost: False
    weight_viapoint: 0
   
   
    # Homotopy Class Planner
   
    enable_homotopy_class_planning: True
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 4
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 5
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: False
