controller_frequency: 20

recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

aggressive_reset:
    reset_distance: 0.0

TrajectoryPlannerROS:

    max_vel_x: 0.30
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_vel_theta: -1.0

    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    acc_lim_y: 1.0

    holonomic_robot: false

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.5

    publish_cost_grid_pc: true
    escape_vel: 0
