controller_frequency: 15

TrajectoryPlannerROS:

    max_vel_x: 0.40
    min_vel_x: 0.1
    max_vel_theta: 3.0
    min_vel_theta: -3.0
    min_in_place_vel_theta: 0.1

    acc_lim_theta: 30.0
    acc_lim_x: 1.0
    acc_lim_y: 1.0

    holonomic_robot: false

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.5
    latch_xy_goal_tolerance: false

    meter_scoring: true
