obstacle_range: 3.0
raytrace_range: 3.0

footprint: [
    [ 0.175, 0.375],
    [ -0.227, 0.375],
    [ -0.227, 0.341],
    [ -0.717, 0.341],
    [ -0.717, 0.147],
    [ -0.898, 0.147],
    [ -0.898, -0.147],
    [ -0.717, -0.147],
    [ -0.717, -0.341],
    [ -0.227, -0.341],
    [ -0.227, -0.375],
    [ 0.175, -0.375],
    [ 0.175, 0.375],
]

# footprint_padding: 0.01
inflation_radius: 0.2

obstacle_layer:

    observation_sources: point_cloud_sensor0 point_cloud_sensor1

    point_cloud_sensor0: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0
    }

    point_cloud_sensor1: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo1/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0
    }
