obstacle_range: 2.5
raytrace_range: 3.0
footprint: [
    [ 0.175, 0.375],
    [ -0.227, 0.375],
    [ -0.227, 0.341],
    [ -0.717, 0.341],
    [ -0.717, 0.147],
    [ -0.898, 0.147],
    [ -0.898, -0.147],
    [ -0.717, -0.147],
    [ -0.717, -0.341],
    [ -0.227, -0.341],
    [ -0.227, -0.375],
    [ 0.175, -0.375],
    [ 0.175, 0.375],
]

footprint_padding: 0.05
inflation_radius: 0.75
transform_tolerance: 1


NavfnROS:
        allow_unknown: false

recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]
