obstacle_range: 10.0
raytrace_range: 10.0

footprint: [
   [ 0.4, 0.36],
   [ -0.5, 0.36],
   [ -0.5, -0.36],
   [ 0.4, -0.36],
]

footprint_padding: 0.00

static_layer:
    enabled:              true
    map_topic:            "/grid_map"

obstacle_layer:

    observation_sources: point_cloud_sensor0 point_cloud_sensor1

    point_cloud_sensor0: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor1: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo1/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }
