obstacle_range: 2.0
raytrace_range: 2.0

frequency: 1.0
goal_aliasing: 1
track_unknown_space: true
global_frame: map
rolling_window: false
# height: 50
# width: 50

plugins: 
- {name: static_layer,          type: "costmap_2d::StaticLayer"}
- {name: explore_boundary,      type: "frontier_exploration::BoundedExploreLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
- {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

explore_boundary:
    resize_to_boundary: false
    frontier_travel_point: middle
    #set to false for gmapping, true if re-exploring a known area
    explore_clear_space: true
