obstacle_range: 10.0
raytrace_range: 10.0

footprint: [
   [ 0.4, 0.36],
   [ -0.5, 0.36],
   [ -0.5, -0.36],
   [ 0.4, -0.36],
]

footprint_padding: 0.03

static_layer:
    enabled:                true
    # map_topic:              "/map_mod"
    map_topic:              "/grid_map"
    track_unknown_space:    false 
    trinary_costmap:        false
    use_maximum:            true

obstacle_layer:

    footprint_clearing_enabled: true

    observation_sources: point_cloud_sensor0 point_cloud_sensor1

    point_cloud_sensor0: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo0/vxl/output, 
        # topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor1: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo1/vxl/output, 
        # topic: /stereo1/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor2: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo2/vxl/output, 
        # topic: /stereo2/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

inflation_layer:
    cost_scaling_factor: 1.0
    inflation_radius: 3.0
