obstacle_range: 6.0
raytrace_range: 10.0

footprint: [
   [  0.40,  0.36],
   [ -0.43,  0.36],
   [ -0.43,  0.08],
   [ -0.54,  0.08],
   [ -0.54, -0.08],
   [ -0.43, -0.08],
   [ -0.43, -0.36],
   [  0.40, -0.36],
]

footprint_padding: 0.005

static_layer:
    enabled:                true
    # map_topic:              "/map_mod"
    map_topic:              "/grid_map"
    track_unknown_space:    false 
    trinary_costmap:        false
    use_maximum:            true

lanes_layer:
    enabled:                true
    # map_topic:              "/map_mod"
    map_topic:              "/lanes"
    track_unknown_space:    false 
    trinary_costmap:        false
    use_maximum:            true

obstacle_layer:

    footprint_clearing_enabled: false

    observation_sources: point_cloud_sensor0 point_cloud_sensor1 point_cloud_sensor2 point_cloud_sensor3

    point_cloud_sensor0: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo0/vxl/output, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor1: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo1/vxl/output, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor2: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo2/vxl/output, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

    point_cloud_sensor3: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo3/vxl/output, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0,
        observation_persistence: 0.0
    }

