obstacle_range: 30.0
raytrace_range: 30.0

footprint: [
   [ 0.4, 0.36],
   [ -0.5, 0.36],
   [ -0.5, -0.36],
   [ 0.4, -0.36],
   # [ 0.45, 0.375],
   # [ -0.45, 0.375],
   # [ -0.45, -0.375],
   # [ 0.45, -0.375],
]

footprint_padding: -0.01

inflation_layer:
    cost_scaling_factor: 3.0
    inflation_radius: 1

obstacle_layer:

    observation_sources: point_cloud_sensor0 point_cloud_sensor1

    point_cloud_sensor0: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.3,
        max_obstacle_height: 2.0,
        observation_persistence: 0
    }

    point_cloud_sensor1: {
        sensor_frame: base_link, 
        data_type: PointCloud2, 
        topic: /stereo1/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0,
        observation_persistence: 0
    }
