global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 3.0
    publish_frequency: 1.0
    static_map: true
    # The size will get reset by the map subscription
    # height: 50
    # width: 50
    rolling_window: false
    resolution: 0.05

    obstacle_layer:
        footprint_clearing_enable: false

    static_layer:
        enabled:                true
        map_topic:              "/grid_map"
        track_unknown_space:    false 

    lanes_layer:
        enabled:              true
        map_topic:            "/lanes"
        # track_unknown_space:    false 
        # use_maximum:            true

    plugins:
        - {name: static_layer,              type: "costmap_2d::StaticLayer"}
        - {name: lanes_layer,               type: "costmap_2d::ObstacleLayer"}
        - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
