global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 3.0
    static_map: true
    height: 50
    width: 50
    rolling_window: true
    resolution: 0.05
    
plugins:
    - {name: static_layer,              type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_global_layer,    type: "costmap_2d::InflationLayer"}

inflation_layer:
    cost_scaling_factor: 1.0
    inflation_radius: 2.5
