global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 3.0
    static_map: true
    height: 30
    width: 30
    resolution: 0.05
    
plugins:
    - {name: static_layer,          type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

