local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 4.0
    static_map: false
    rolling_window: true
    width: 2.0
    height: 2.0
    resolution: 0.05

obstacle_layer:

    observation_sources: point_cloud_sensor

    point_cloud_sensor: {
        sensor_frame: stereo0_link, 
        data_type: PointCloud2, 
        topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 2.0
    }
