local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 3.0
    rolling_window: true
    static_map: false
    width: 10.0
    height: 10.0
    resolution: 0.02

    plugins:
        - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

    inflation_layer:
        cost_scaling_factor: 1.5
        inflation_radius: 0.7
