local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 3.0
    rolling_window: true
    static_map: false
    width: 4.0
    height: 4.0
    resolution: 0.02

plugins:
    - {name: static_layer,              type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_local_layer,     type: "costmap_2d::InflationLayer"}
