local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 4.0
    static_map: false
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.02

    plugins:
    - {name: static_layer,          type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}
    # - {name: obstacle_layer,        type: "costmap_2d::InflationLayer"}

# obstacle_layer:
#
#     observation_sources: point_cloud_sensor0 point_cloud_sensor1
#
#     point_cloud_sensor0: {
#         sensor_frame: base_link, 
#         data_type: PointCloud2, 
#         topic: /stereo0/points2, 
#         marking: true, 
#         clearing: true,
#         min_obstacle_height: 0.3,
#         max_obstacle_height: 2.0,
#         observation_persistence: 0.1
#     }
#
#     point_cloud_sensor1: {
#         sensor_frame: base_link, 
#         data_type: PointCloud2, 
#         topic: /stereo1/points2, 
#         marking: true, 
#         clearing: true,
#         min_obstacle_height: 0.5,
#         max_obstacle_height: 2.0,
#         observation_persistence: 0.1
#     }
