local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 3.0
    rolling_window: true
    static_map: false
    width: 2.0
    height: 2.0
    resolution: 0.02

    plugins:
        - {name: obstacle_layer,    type: 'decaying_layer::DecayingObstacleLayer'}  
        - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
