local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    rolling_window: true
    static_map: true
    width: 4.0
    height: 4.0
    resolution: 0.02
