obstacle_range: 3.0
raytrace_range: 6.0
footprint: [
    [ 0.175, 0.375],
    [ -0.227, 0.375],
    [ -0.227, 0.341],
    [ -0.717, 0.341],
    [ -0.717, 0.147],
    [ -0.898, 0.147],
    [ -0.898, -0.147],
    [ -0.717, -0.147],
    [ -0.717, -0.341],
    [ -0.227, -0.341],
    [ -0.227, -0.375],
    [ 0.175, -0.375],
    [ 0.175, 0.375],
]

footprint_padding: 0.01
# robot_radius: 0.5
inflation_radius: 0.01

NavfnROS:
        allow_unknown: true


obstacle_layer:

    observation_sources: point_cloud_sensor

    point_cloud_sensor: {
        sensor_frame: stereo0_link, 
        data_type: PointCloud2, 
        topic: /stereo0/points2, 
        marking: true, 
        clearing: true,
        min_obstacle_height: 0.5,
        max_obstacle_height: 1.0
    }
