# This is the config file for the velocity smoother.
# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_v: 0.7
speed_lim_w: 0.7

accel_lim_v: 1.0
accel_lim_w: 1.0

# Optional parameters
frequency: 30.0
decel_factor: 2.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0
