frequency: 30
sensor_timeout: 0.1
two_d_mode: false
publish_tf: true

map_frame: map              # Defaults to "map" if unspecified
odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified


# Wheel odom
odom0: wheel/odom
odom0_config: [false, false, false,
               false, false, true,
               true,  true,  true,
               false, false, true,
               false, false, false]
odom0_queue_size: 2
odom0_nodelay: false
odom0_differential: false
odom0_relative: false

# Visual odom
odom1: stereo1/odom
odom1_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]
odom1_queue_size: 2
odom1_nodelay: false
odom1_differential: false
odom1_relative: false

# IMU
imu0: imu_data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
imu0_nodelay: false
imu0_differential: false
imu0_relative: true
imu0_queue_size: 5
imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
imu0_twist_rejection_threshold: 0.8                #
imu0_linear_acceleration_rejection_threshold: 0.8  #

