frequency: 30
sensor_timeout: 0.1
two_d_mode: true
publish_tf: true

print_diagnostics: true

map_frame: map              # Defaults to "map" if unspecified
odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified

# Be careful with numbers of the odom tags, must be sequential and start at 0

# Wheel odom
odom0: wheel/odom
odom0_config: [false, false, false,
               false, false, false,
               true,  true, false,
               false, false, true,
               false, false, false]
odom0_queue_size: 2

#Visual odom
odom1: stereo_odom/odom
odom1_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom1_queue_size: 2
# added this after experimentation.
odom1_twist_rejection_threshold: 0.2

# IMU
# Just use the angular gyro. That is it.
imu0: imu
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false,  false,  true,
              true,  false,  false]
# imu0_nodelay: false
imu0_queue_size: 2
imu0_twist_rejection_threshold: 0.15
