obstacle_range: 30.0
raytrace_range: 30.0

footprint: [
   [ 0.4, 0.36],
   [ -0.5, 0.36],
   [ -0.5, -0.36],
   [ 0.4, -0.36],
]

footprint_padding: -0.00

# inflation_layer:
#     cost_scaling_factor: 1.
#     inflation_radius: 2.5
#
# static_layer:
#     enabled:              true
#     map_topic:            "/map"
