!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 160.0
  P2: 400.0
  correlation_window_size: 53
  disp12MaxDiff: 17
  disparity_range: 96
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 160.0
      P2: 400.0
      correlation_window_size: 53
      disp12MaxDiff: 17
      disparity_range: 96
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: -42
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 42
      prefilter_size: 39
      speckle_range: 4
      speckle_size: 10
      state: true
      stereo_algorithm: 0
      texture_threshold: 5948
      type: ''
      uniqueness_ratio: 18.0
    state: []
  min_disparity: -42
  prefilter_cap: 42
  prefilter_size: 39
  speckle_range: 4
  speckle_size: 10
  stereo_algorithm: 0
  texture_threshold: 5948
  uniqueness_ratio: 18.0
state: []
