stereo0:
    disparity:
        texture_threshold: 2500
        speckle_size: 1000
        disparity_range: 128
        correlation_window_size: 17

stereo1:
    stereo_image_proc:
        texture_threshold: 2500
        speckle_size: 1000
        uniqueness_ratio: 50
        disparity_range: 128
        correlation_window_size: 17

    disparity:
        texture_threshold: 2500
        speckle_size: 1000
        disparity_range: 128
        correlation_window_size: 17

stereo2:
    stereo_image_proc:
        texture_threshold: 3000
        speckle_size: 1000
        uniqueness_ratio: 50
        disparity_range: 128
        correlation_window_size: 17

    disparity:
        texture_threshold: 2500
        speckle_size: 1000
        disparity_range: 128
        correlation_window_size: 17

# /stereo0/disparity/P1
# /stereo0/disparity/P2
# /stereo0/disparity/correlation_window_size
# /stereo0/disparity/disp12MaxDiff
# /stereo0/disparity/disparity_range
# /stereo0/disparity/fullDP
# /stereo0/disparity/min_disparity
# /stereo0/disparity/prefilter_cap
# /stereo0/disparity/prefilter_size
# /stereo0/disparity/speckle_range
# /stereo0/disparity/speckle_size
# /stereo0/disparity/stereo_algorithm
# /stereo0/disparity/texture_threshold
# /stereo0/disparity/uniqueness_ratio
